from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
import os, sys
import folium
sys.path.append("/Users/richardpears/DRT_ideahack")

app = FastAPI()

import src.data.drt_gtfs as gtfs


# Serve the map generated by gtfs.create_combined_map


@app.get("/", response_class=HTMLResponse)
async def read_root():
    try:
        static_routes_data = gtfs.fetch_static_routes()
        combined_map = gtfs.create_combined_map(
            gtfs.vehicles, static_routes_data, gtfs.durham_center
        )
        combined_map_html = combined_map.get_root().render()
        return HTMLResponse(content=combined_map_html, status_code=200)
    except Exception as e:
        return HTMLResponse(
            content=f"<h1>Error generating map: {str(e)}</h1>", status_code=500
        )